name: AWS CDK Synth

on: [push]

jobs:
  aws-cdk-synth:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: npm-run-build
      run:  cd ./cloud &&  npm install && npm run build
      
    - name: CDK Synth
      uses: scottbrenner/aws-cdk-action@master
      
      with:
        args: deploy
        working_dir: ./cloud
        
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
